// Code generated by protoc-gen-typescript-http. DO NOT EDIT.
/* eslint-disable camelcase */
// @ts-nocheck

// 错误原因
export type ErrorReason =
  // 用户名未指定
  | "GREETER_UNSPECIFIED"
  // 用户不存在
  | "USER_NOT_FOUND";
// HelloRequest 类型定义了打招呼参数类型
export type HelloRequest = {
  // 用户名
  name: string | undefined;
};

// HelloReply 类型是打招呼的返回信息类型
export type HelloReply = {
  // 响应信息
  message: string | undefined;
};

// Greeter 服务是打招呼服务
export interface Greeter {
  // SayHello 方法进行一个招呼的打。
  // 当用户名为 "404" 时应报错。错误原因是 "USER_NOT_FOUND"。
  // 当用户名为 "400" 时应报错。错误原因是 "GREETER_UNSPECIFIED"。
  SayHello(request: HelloRequest): Promise<HelloReply>;
}

type RequestType = {
  path: string;
  method: string;
  body: string | null;
};

type RequestHandler = (request: RequestType, meta: { service: string, method: string }) => Promise<unknown>;

export function createGreeterClient(
  handler: RequestHandler
): Greeter {
  return {
    SayHello(request) { // eslint-disable-line @typescript-eslint/no-unused-vars
      if (!request.name) {
        throw new Error("missing required field request.name");
      }
      const path = `helloworld/${request.name}`; // eslint-disable-line quotes
      const body = null;
      const queryParams: string[] = [];
      let uri = path;
      if (queryParams.length > 0) {
        uri += `?${queryParams.join("&")}`
      }
      return handler({
        path: uri,
        method: "GET",
        body,
      }, {
        service: "Greeter",
        method: "SayHello",
      }) as Promise<HelloReply>;
    },
  };
}

// @@protoc_insertion_point(typescript-http-eof)
